/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function resolveRs(
  importer: string,
  importee: string,
  conditionNames: Array<string>,
  mainFields: Array<string>,
  extensions: Array<string>,
): string
export declare function isBarrelFileRs(source: string, amountOfExportsToConsiderModuleAsBarrel: number): boolean
export declare function countModuleGraphSizeRs(
  entryPoints: Array<string>,
  basePath: string,
  conditionNames: Array<string>,
  mainFields: Array<string>,
  extensions: Array<string>,
  builtinModules: Array<string>,
  tsconfigConfigFile: string | undefined | null,
  tsconfigReferences: Array<string> | undefined | null,
  alias: Array<[string, Array<string>]>,
): number
